### PR TITLE
Update Makefile to add latest wolfssl version and remove arch specific flags to gcc

### PR DESCRIPTION
**Pull request by piyushgupta1551**

### CODE REVIEW

**Comment by jmencak** [comment]
Thank you for the PR, looks good.  I understand the reasoning for dropping the architecture-specific flags, however, did you test the impact of dropping `enable-aesni` and `enable-intelasm`?  In the past I specifically wrote this project for Intel architectures with the aim to squeeze the maximum performance on them.

**Comment by piyushgupta1551** [comment]
Hi @jmencak , Yes I have removed the flags, built an image (using [this](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/router-perf-v2/Containerfile) file) and have tested it on a ppc64le (P9) OCP 4.7 cluster and it ran to completion without any issues. From an Intel standpoint, the mb image would need to be rebuilt and tested to evaluate any potential impact. Probably the perf-scale team at RH can trigger one of their workflows to do that in an automated way?

Also I agree that the purpose of adding them was to enhance the performance but unfortunately I don't have any comparison/baseline data to evaluate how removing these flags would impact the overall performance in general.

**Comment by jmencak** [comment]
I did some microbenchmarking on a passively cooled "Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz", 4 cores, 8 threads and nginx server running on the same box.

request-https.json
```
[
  {
    "host": "127.0.0.1",
    "port": 8443,
    "scheme": "https",
    "tls-session-reuse": true,
    "method": "GET",
    "path": "/1024.html",
    "keep-alive-requests": 100,
    "clients": 40,
    "delay": {
      "min": 0,
      "max": 0,
    },
    "close": {
       "client": false,
    }
  },
]
```

### The old wolfssl-3.12.2 library

```
# aesni on and intelasm on
$ ./mb -d60 -i request-https.json                                                                                                                                            
Time: 60.08s                                                                                                                                                                                   
Sent: 645.18MiB, 10.74MiB/s
Recv: 8.73GiB, 148.72MiB/s
Hits: 7418840, 123474.34/s

# aesni on and intelasm off
$ ./mb -d60 -i request-https.json                                                                                                                                            
Time: 60.07s                                                                                                                                                                                   
Sent: 637.19MiB, 10.61MiB/s
Recv: 8.62GiB, 146.91MiB/s
Hits: 7326894, 121969.74/s

# aesni off and intelasm off
$ ./mb -d60 -i request-https.json                                                                                                                                            
Time: 60.08s                                                                                                                                                                                   
Sent: 391.63MiB, 6.52MiB/s
Recv: 5.30GiB, 90.28MiB/s
Hits: 4503270, 74953.05/s
```
### The new wolfssl-4.7.0 library

```
# aesni on and intelasm on
$ ./mb -d60 -i request-https.json                                                                                                                                            
Time: 60.09s                                                                                                                                                                                   
Sent: 646.17MiB, 10.75MiB/s
Recv: 8.74GiB, 148.94MiB/s
Hits: 7430149, 123658.27/s

# aesni on and intelasm off
$ ./mb -d60 -i request-https.json                                                                                                                                            
Time: 60.09s                                                                                                                                                                                   
Sent: 628.24MiB, 10.46MiB/s
Recv: 8.50GiB, 144.80MiB/s
Hits: 7224037, 120220.86/s

# aesni off and intelasm off
./mb -d60 -i request-https.json                                                                                                                                            
Time: 60.06s                                                                                                                                                                                   
Sent: 480.27MiB, 8.00MiB/s
Recv: 6.50GiB, 110.75MiB/s
Hits: 5522489, 91951.36/s
```

So, definitely an improvement with the new library when not using *aesni*, however, we really want to use *aesni* for architectures that support it.  This will need a bit more thought and work as this PR would result in performance penalty for architectures with *aesni* support.  Will need to think about how to approach this best.

**Comment by piyushgupta1551** [comment]
Can we move this PR to a different/new ppc64le branch maybe? 
I will anyways need to create a ppc64le specific Dockerfile for building the mb image (https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/router-perf-v2/Containerfile) due to some python related issues.
I can change the repo reference inside the Containerfile to `git clone -b <new branch> https://github.com/jmencak/mb.git`
That ways Intel/AMD users wont miss out on using these performance flags. But yes, I understand that maintaining different branches is not the best way ahead in long term but the only quickest and non-impacting one I can think of.

**Comment by jmencak** [comment]
The branch idea sounds like a maintenance nightmare.  I think we need a way to pass parameters to the `./configure` for wolfssl and/or figure out the correct options within the Makefile.  Let me create a PR and I'll tag you on it.  I also need to fix compilation with gcc 11.  It no longer compiles.

**Comment by jmencak** [comment]
@piyushgupta1551 I decided to keep this clean and architecture independent.  If you think the https://github.com/jmencak/mb/pull/7 is sane, please comment there.  Thank you for your contribution!

**Comment by piyushgupta1551** [comment]
I think its a great approach but will need a subsequent change here - https://github.com/cloud-bulldozer/e2e-benchmarking/blob/5ba2761e8fe55b74b1626e8bceafdd36fd45458a/workloads/router-perf-v2/Containerfile#L4 to enable Intel builds to pass these flags.
I can raise that PR so should be fine. Since I anyways need to create a separate Containerfile for ppc64le, this change works for me too. I 'm guessing these changes have been tested by you otherwise.
Please go ahead and merge #7 . I will raise the PR for the subsequent change needed in the e2e-benchmarking repository.
Tx @jmencak !

**Comment by jmencak** [comment]
Closing in favour of https://github.com/jmencak/mb/pull/7, thank you for following through with the rest!

**Pull request closed without merging**
